export const WORD_SELECTED = "WORD_SELECTED";
export const FETCH_SYNONYMS_BEGIN = "FETCH_SYNONYMS_BEGIN";
export const FETCH_SYNONYMS_SUCCESS = "FETCH_SYNONYMS_SUCCESS";
export const FETCH_SYNONYMS_FAIL = "FETCH_SYNONYMS_FAIL";
export const SET_HEADWORD = "SET_HEADWORD";
